# This workflow will publish to PyPi on a new tag.
name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read
  # IMPORTANT: this permission is mandatory for trusted publishing
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/flashkit

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.5
      uses: actions/setup-python@v3
      with:
        python-version: "3.5"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatchling
        pip install -r requirements.txt

    - name: Set the version number
      run: |
        sed -e 's/version = ".*"/version = "${{ github.ref_name }}"/' -i pyproject.toml
        # FIXME: Debugging before actual first publication
        cat pyproject.toml
        exit 1

    - name: Build with Hatchling
      run: hatchling build

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
